# ~/.config/starship.toml

add_newline = false

[line_break]
disabled = true

[kubernetes]
disabled = true

[terraform]
disabled = true

[aws]
disabled = true

[python]
disabled = true

[golang]
disabled = true

[cmd_duration]
disabled = true

