# ~/.config/starship.toml

add_newline = false

[line_break]
disabled = true

[kubernetes]
style = "cyan dimmed"
format = '[$symbol$context]($style) in '
disabled = false
[kubernetes.context_aliases]
"arn:aws:eks:eu-central-1:317566953396:cluster/mesh-eks-gloo-dev-euc1" = "transit-dev-euc1"

[terraform]
disabled = true

[aws]
disabled = true

[python]
disabled = true

[golang]
disabled = true

[cmd_duration]
disabled = true

[dart]
disabled = true

